## Demo of the 3D Cell Generation API

This notebook demonstrates how to get a cell type population for anatomical structures (ASpop) from HRApop, formulate a request for the 3D Cell Generation API, and display the result in 3D using the `node-dist-vis` HRA Jupyter Widgets.

## Install and import libraries

In [146]:
%pip install requests pandas hra_jupyter_widgets ipywidgets

import requests
import json
from io import StringIO
import pandas as pd
from pprint import pprint

Requirement already satisfied: requests in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (2.32.3)
Requirement already satisfied: pandas in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (2.2.3)
Requirement already satisfied: hra_jupyter_widgets in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (0.4.1)
Requirement already satisfied: ipywidgets in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (8.1.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from requests) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from requests) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from requests) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from requests) (2025.1.31)
Requirement already satisfied: numpy>=1.26.0 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from pandas) (2.2.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: anywidget in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from hra_jupyter_widgets) (0.9.18)
Requirement already satisfied: traitlets>=5.10 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from hra_jupyter_widgets) (5.14.3)
Requirement already satisfied: comm>=0.1.3 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipywidgets) (0.2.2)
Requirement already satisfied: ipython>=6.1.0 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipywidgets) (9.0.2)
Requirement already satisfied: widgetsnbextension~=4.0.14 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipywidgets) (4.0.14)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipywidgets) (3.0.15)
Requirement already satisfied: decorator in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.16 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: pexpect>4.3 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (4.9.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (3.0.50)
Requirement already satisfied: pygments>=2.4.0 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (2.19.1)
Requirement already satisfied: stack_data in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: wcwidth in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.13)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.4)
Requirement already satisfied: ptyprocess>=0.5 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from pexpect>4.3->ipython>=6.1.0->ipywidgets) (0.7.0)
Requirement already satisfied: six>=1.5 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: psygnal>=0.8.1 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from anywidget->hra_jupyter_widgets) (0.14.1)
Requirement already satisfied: typing-extensions>=4.2.0 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from anywidget->hra_jupyter_widgets) (4.13.2)
Requirement already satisfied: executing>=1.2.0 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.0)
Requirement already satisfied: asttokens>=2.1.0 in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in /Users/abueckle/Documents/GitHub/hra-pop-notebooks/.venv/lib/python3.12/site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)

[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

## Import widgets

In [147]:
import ipywidgets as widgets
from hra_jupyter_widgets import (
    NodeDistVis,          # VCCF 3D Node Distance Visualization
)

## Exemplary call to visualize cell type population for the renal pyramid A in the male, left kidney

In [148]:
# get ASpop for the male, left kidney
response = requests.get('https://apps.humanatlas.io/api/grlc/hra-pop/cell_types_in_anatomical_structurescts_per_as.csv', headers = {'accept':'text/csv'})
df_as_pop = pd.read_csv(StringIO(response.text))
df_as_pop

,organ,as,as_label,sex,tool,modality,cell_id,cell_label,cell_count,cell_percentage,dataset_count
0,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_colonocyte,Colonocyte,1.205,0.147653,3
1,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_iga-plasma-cell,IgA plasma cell,1.182,0.144835,3
2,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_best4-epithelial,BEST4+ epithelial,0.699,0.085651,3
3,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_activated-cd4-t,Activated CD4 T,0.690,0.084548,3
4,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_ta,TA,0.540,0.066168,3
...,...,...,...,...,...,...,...,...,...,...,...
8891,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_0000097,Mast Cell,15322.464,0.024702,1
8892,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_4033039,CD8+ T Cell,3691.176,0.005951,1
8893,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,https://purl.org/ccf/ASCTB-TEMP_lymphatic-endo...,Lymphatic Endothelial (and some immune cells),1753.956,0.002828,1
8894,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,https://purl.org/ccf/ASCTB-TEMP_basal-epitheli...,Basal Epithelial Cell,970.104,0.001564,1
8895,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_0000236,B Cell,462.144,0.000745,1

In [149]:
# subset to only keep male left kidney, renal pyramid, azimuth
df_renal_pyramid = df_as_pop[(df_as_pop['organ'] == 'Left kidney')& (df_as_pop['as_label'] == 'renal pyramid') & (df_as_pop['tool'] == 'azimuth') & (df_as_pop['sex']=='Male')]
df_renal_pyramid

,organ,as,as_label,sex,tool,modality,cell_id,cell_label,cell_count,cell_percentage,dataset_count
6055,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001109,Cortical Thick Ascending Limb,105493.791,0.228450,31
6057,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030012,Descending Thin Limb Type 1,48210.290,0.104401,31
6059,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000714,Cortical Collecting Duct Principal,47365.703,0.102572,31
6061,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001108,Medullary Thick Ascending Limb,37587.100,0.081396,31
6063,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000768,Connecting Tubule,36564.115,0.079181,31
6065,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001107,Ascending Thin Limb,28549.937,0.061826,31
6067,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030022,Medullary Fibroblast,28149.594,0.060959,31
6069,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030016,Distal Convoluted Tubule Type 1,21950.691,0.047535,31
6071,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_descending-vas...,Descending Vasa Recta Endothelial,19436.637,0.042091,31
6073,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000718,Inner Medullary Collecting Duct,13973.404,0.030260,31
6075,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030014,Descending Thin Limb Type 3,9374.074,0.020300,31
6077,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000692,Fibroblast,7688.019,0.016649,31
6079,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0002201,Intercalated Type B,6841.483,0.014815,31
6081,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000850,Macula Densa,6573.065,0.014234,31
6083,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001131,Ascending Vasa Recta Endothelial,6114.286,0.013241,31
6085,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030013,Descending Thin Limb Type 2,6053.296,0.013109,31
6087,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000716,Outer Medullary Collecting Duct Principal,3460.530,0.007494,31
6089,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001318,Vascular Smooth Muscle / Pericyte,3008.679,0.006515,31
6091,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000717,Outer Medullary Collecting Duct Intercalated T...,2971.651,0.006435,31
6093,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0011031,Monocyte-derived,2951.421,0.006391,31
6095,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_peritubular-ca...,Peritubular Capilary Endothelial,2368.401,0.005129,31
6097,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000084,T,2249.235,0.004871,31
6099,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030009,Proximal Tubule Epithelial Segment 1,2203.518,0.004772,31
6101,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000452,Parietal Epithelial,2146.141,0.004648,31
6103,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030018,Connecting Tubule Principal,1745.379,0.003780,31
6105,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000890,M2 Macrophage,1463.011,0.003168,31
6107,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000715,Cortical Collecting Duct Intercalated Type A,1426.233,0.003089,31
6109,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001005,Glomerular Capillary Endothelial,1368.161,0.002963,31
6111,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000597,Papillary Tip Epithelial,1084.013,0.002347,31
6113,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000653,Podocyte,1047.483,0.002268,31
6115,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030011,Proximal Tubule Epithelial Segment 3,636.392,0.001378,31
6117,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000412,Afferent / Efferent Arteriole Endothelial,468.172,0.001014,31
6119,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000650,Mesangial,432.708,0.000937,31
6121,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000990,Classical Dendritic,358.000,0.000775,31
6123,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000236,B,152.012,0.000329,31
6125,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030010,Proximal Tubule Epithelial Segment 2,114.691,0.000248,31
6127,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030017,Distal Convoluted Tubule Type 2,38.735,0.000084,31
6129,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000648,Renin-positive Juxtaglomerular Granular,38.547,0.000083,31
6131,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0002138,Lymphatic Endothelial,34.004,0.000074,31
6133,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000097,Mast,34.000,0.000074,31
6135,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000814,Natural Killer T,14.589,0.000032,31
6137,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0002573,Schwann / Neural,13.858,0.000030,31
6139,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000786,Plasma,6.012,0.000013,31
6141,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000775,Neutrophil,6.000,0.000013,31
6143,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030020,Connecting Tubule Intercalated Type A,5.000,0.000011,31
6145,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000875,Non-classical monocyte,4.027,0.000009,31
6147,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4033078,Cycling Mononuclear Phagocyte,4.000,0.000009,31

In [150]:
# filter out cells below threshold such that only n_max CTs remain
n_max = 10

top10 = df_renal_pyramid.nlargest(n_max, "cell_percentage")
top10

,organ,as,as_label,sex,tool,modality,cell_id,cell_label,cell_count,cell_percentage,dataset_count
6055,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001109,Cortical Thick Ascending Limb,105493.791,0.228450,31
6057,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030012,Descending Thin Limb Type 1,48210.290,0.104401,31
6059,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000714,Cortical Collecting Duct Principal,47365.703,0.102572,31
6061,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001108,Medullary Thick Ascending Limb,37587.100,0.081396,31
6063,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000768,Connecting Tubule,36564.115,0.079181,31
6065,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001107,Ascending Thin Limb,28549.937,0.061826,31
6067,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030022,Medullary Fibroblast,28149.594,0.060959,31
6069,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030016,Distal Convoluted Tubule Type 1,21950.691,0.047535,31
6071,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_descending-vas...,Descending Vasa Recta Endothelial,19436.637,0.042091,31
6073,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000718,Inner Medullary Collecting Duct,13973.404,0.030260,31

In [151]:
# transform into dict so it can be used in the payload for the API request

In [152]:
node_distribution = dict(zip(top10['cell_label'], top10['cell_percentage']))
pprint(node_distribution)

{'Ascending Thin Limb': 0.06182582952775565,
 'Connecting Tubule': 0.07918079611955897,
 'Cortical Collecting Duct Principal': 0.1025719909343514,
 'Cortical Thick Ascending Limb': 0.2284502812949354,
 'Descending Thin Limb Type 1': 0.1044009719189105,
 'Descending Vasa Recta Endothelial ': 0.04209067801988033,
 'Distal Convoluted Tubule Type 1': 0.04753494481555039,
 'Inner Medullary Collecting Duct': 0.03025986690010765,
 'Medullary Fibroblast': 0.06095887356667489,
 'Medullary Thick Ascending Limb': 0.08139610385279325}

In [153]:
def call_3d_cell_api(file: str, scene_node: str, num_nodes: int, node_distribution: dict):
  """Wrapper function to make a call to the 3D Cell Generation API using a payload constructed with user-provided arguments

  Args:
      file (str): the link to the GLB file of the organ, see, e.g., https://apps.humanatlas.io/api#get-/v1/reference-organs
      scene_node (str): the scene node of the AS
      num_nodes (int): the max. total number of cells
      node_distribution (dict): a dict with key-value-pairs for cell label and percentages [0,1]
  """

  url = 'https://apps.humanatlas.io/api/v1/mesh-3d-cell-population'

  payload = {
      'file': file,
      'file_subpath': scene_node,
      'num_nodes': num_nodes,
      'node_distribution': node_distribution
  }

  headers = {
      'Content-Type': 'application/json'
  }

  try:
      response = requests.post(url, data=json.dumps(payload), headers=headers)
      response.raise_for_status()  # Raise an exception for HTTP errors (4xx or 5xx)
      return pd.read_csv(StringIO(response.text))
      print("Response Status Code:", response.status_code)
      print("Response JSON:", response.json())
  except requests.exceptions.RequestException as e:
      print(f"An error occurred: {e}")
      return None

In [154]:
# make request
result = call_3d_cell_api(
    file='https://cdn.humanatlas.io/digital-objects/ref-organ/kidney-male-left/v1.3/assets/3d-vh-m-kidney-l.glb',
    scene_node='VH_M_renal_pyramid_L_a',
    num_nodes=10000,
    node_distribution=node_distribution
)
result

             x         y         z                        Cell Type
0     0.055965  0.329988 -0.034418    Cortical Thick Ascending Limb
1     0.057161  0.333525 -0.048311    Cortical Thick Ascending Limb
2     0.058807  0.333977 -0.046260    Cortical Thick Ascending Limb
3     0.060055  0.329908 -0.045638    Cortical Thick Ascending Limb
4     0.055005  0.325174 -0.045930    Cortical Thick Ascending Limb
...        ...       ...       ...                              ...
8376  0.054682  0.332450 -0.049931  Inner Medullary Collecting Duct
8377  0.054572  0.339244 -0.037392  Inner Medullary Collecting Duct
8378  0.050174  0.324458 -0.034496  Inner Medullary Collecting Duct
8379  0.053084  0.341663 -0.052267  Inner Medullary Collecting Duct
8380  0.050174  0.327949 -0.031868  Inner Medullary Collecting Duct

[8381 rows x 4 columns]

In [155]:
# Next, let's define a function that turns a DataFrame into a node list that can then be passed into the CdeVisualization or NodeDistVis widget
def make_node_list(df: pd.DataFrame, is_3d: bool = False):
  """Turn a DataFrame into a list of dicts for passing them into a HRA widget

  Args:
      df (pd.DataFrame): A DataFrame with cells
  """

  # If the df does not have a z-axis column, let's add one and set all cells to 0
  if not is_3d:
    df.loc[:, ('z')] = 0

  node_list = [{'x': row['x'], 'y': row['y'], 'z': row['z'], 'Cell Type': row['Cell Type']}
               for index, row in df.iterrows()]

  return node_list

In [156]:
node_list = make_node_list(result, True)
node_list

[{'x': 0.0559646,
  'y': 0.329988,
  'z': -0.0344179,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0571613,
  'y': 0.333525,
  'z': -0.0483111,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.058807,
  'y': 0.333977,
  'z': -0.0462597,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.060055,
  'y': 0.329908,
  'z': -0.0456385,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0550052,
  'y': 0.325174,
  'z': -0.0459305,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0513232,
  'y': 0.338971,
  'z': -0.0385146,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0454906,
  'y': 0.332285,
  'z': -0.0302794,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0563854,
  'y': 0.339257,
  'z': -0.0508255,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0511856,
  'y': 0.330039,
  'z': -0.0334309,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0585665,
  'y': 0.327487,
  'z': -0.0443972,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0512985,
  'y': 0.337681,
  'z': -0.034826,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0546088,
  'y': 0.339519,
  'z': -0.0509258,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0502124,
  'y': 0.342036,
  'z': -0.040603,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0565463,
  'y': 0.332716,
  'z': -0.0400302,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0481804,
  'y': 0.335115,
  'z': -0.0287503,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0447294,
  'y': 0.329453,
  'z': -0.0224448,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0547983,
  'y': 0.333781,
  'z': -0.0286028,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0538375,
  'y': 0.339087,
  'z': -0.0503595,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0588599,
  'y': 0.336218,
  'z': -0.0388353,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0494825,
  'y': 0.331415,
  'z': -0.0347694,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0529967,
  'y': 0.324397,
  'z': -0.0328446,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0525776,
  'y': 0.32514,
  'z': -0.0342386,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0452056,
  'y': 0.330409,
  'z': -0.033291,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0427371,
  'y': 0.333294,
  'z': -0.0254025,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0456158,
  'y': 0.328101,
  'z': -0.0281685,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0562895,
  'y': 0.33889,
  'z': -0.0431842,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.046082,
  'y': 0.323931,
  'z': -0.0245364,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0492737,
  'y': 0.334958,
  'z': -0.0367951,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0589435,
  'y': 0.329846,
  'z': -0.0481143,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0508658,
  'y': 0.331123,
  'z': -0.0313892,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0606287,
  'y': 0.329797,
  'z': -0.0438714,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0576052,
  'y': 0.330342,
  'z': -0.0211235,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0517939,
  'y': 0.333467,
  'z': -0.0397077,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0524024,
  'y': 0.33291,
  'z': -0.0261234,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0588996,
  'y': 0.331653,
  'z': -0.0374578,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0475075,
  'y': 0.332955,
  'z': -0.0374161,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0609704,
  'y': 0.336115,
  'z': -0.0514875,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0572187,
  'y': 0.339245,
  'z': -0.0347628,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0543457,
  'y': 0.328362,
  'z': -0.0327021,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0606708,
  'y': 0.33754,
  'z': -0.0503457,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0594405,
  'y': 0.330096,
  'z': -0.0447721,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0542505,
  'y': 0.323761,
  'z': -0.0313749,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0584409,
  'y': 0.32964,
  'z': -0.0269616,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0600997,
  'y': 0.345895,
  'z': -0.0546866,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.051386,
  'y': 0.329735,
  'z': -0.0310313,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0581945,
  'y': 0.335829,
  'z': -0.0312421,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0554803,
  'y': 0.340913,
  'z': -0.0423378,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0476969,
  'y': 0.322286,
  'z': -0.0235727,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0580254,
  'y': 0.345815,
  'z': -0.0533096,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0587395,
  'y': 0.339543,
  'z': -0.0543655,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0462988,
  'y': 0.326942,
  'z': -0.0240247,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.051015,
  'y': 0.319994,
  'z': -0.0317155,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0560095,
  'y': 0.343502,
  'z': -0.0524324,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0572901,
  'y': 0.33226,
  'z': -0.028779,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0583362,
  'y': 0.327815,
  'z': -0.0232465,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.048315,
  'y': 0.326487,
  'z': -0.0369064,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0628904,
  'y': 0.3302,
  'z': -0.041705,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0478745,
  'y': 0.328833,
  'z': -0.0251135,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.055172,
  'y': 0.329688,
  'z': -0.0358659,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0522051,
  'y': 0.33327,
  'z': -0.0269827,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0587782,
  'y': 0.332531,
  'z': -0.0323729,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0489443,
  'y': 0.328316,
  'z': -0.0228907,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0591222,
  'y': 0.34644,
  'z': -0.0573535,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0512756,
  'y': 0.317613,
  'z': -0.0305245,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0543903,
  'y': 0.341332,
  'z': -0.0391944,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0583924,
  'y': 0.343615,
  'z': -0.0544375,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0430921,
  'y': 0.33197,
  'z': -0.0296183,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0542173,
  'y': 0.334903,
  'z': -0.0319808,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0561342,
  'y': 0.337926,
  'z': -0.050781,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0499701,
  'y': 0.343126,
  'z': -0.0417889,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0600417,
  'y': 0.334343,
  'z': -0.0441237,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0561518,
  'y': 0.335836,
  'z': -0.0445276,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0541993,
  'y': 0.329558,
  'z': -0.0379817,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0476561,
  'y': 0.326744,
  'z': -0.033118,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0534542,
  'y': 0.335033,
  'z': -0.0417468,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0582203,
  'y': 0.339456,
  'z': -0.0434221,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0563125,
  'y': 0.336405,
  'z': -0.0267571,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.046191,
  'y': 0.334966,
  'z': -0.0335392,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0493707,
  'y': 0.334194,
  'z': -0.0359117,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0541886,
  'y': 0.335375,
  'z': -0.0375355,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0560746,
  'y': 0.338512,
  'z': -0.0400048,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0487567,
  'y': 0.33321,
  'z': -0.0336651,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0503871,
  'y': 0.345323,
  'z': -0.0428483,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0540553,
  'y': 0.337616,
  'z': -0.0402535,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0491722,
  'y': 0.333547,
  'z': -0.033476,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0543551,
  'y': 0.334243,
  'z': -0.0437678,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.049583,
  'y': 0.329603,
  'z': -0.0278756,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0569878,
  'y': 0.332836,
  'z': -0.028027,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0565057,
  'y': 0.340862,
  'z': -0.0521404,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0581544,
  'y': 0.330361,
  'z': -0.0312874,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0529622,
  'y': 0.336461,
  'z': -0.0270794,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0548287,
  'y': 0.329189,
  'z': -0.0381537,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0564152,
  'y': 0.33116,
  'z': -0.0304892,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0547834,
  'y': 0.33305,
  'z': -0.0243905,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0550848,
  'y': 0.334675,
  'z': -0.0283077,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0494702,
  'y': 0.324916,
  'z': -0.0273687,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0443099,
  'y': 0.331081,
  'z': -0.0218865,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.057013,
  'y': 0.327049,
  'z': -0.0497336,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0603053,
  'y': 0.344276,
  'z': -0.0555164,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0568578,
  'y': 0.324738,
  'z': -0.0435456,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0613227,
  'y': 0.33204,
  'z': -0.0335329,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0513919,
  'y': 0.3406,
  'z': -0.0349805,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.059459,
  'y': 0.335507,
  'z': -0.0276367,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0544919,
  'y': 0.336879,
  'z': -0.0378812,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0506338,
  'y': 0.323885,
  'z': -0.03058,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0544093,
  'y': 0.334826,
  'z': -0.0331736,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0584379,
  'y': 0.340306,
  'z': -0.0377295,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0544391,
  'y': 0.339861,
  'z': -0.0404254,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0505605,
  'y': 0.327719,
  'z': -0.0234934,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.055482,
  'y': 0.338399,
  'z': -0.0435518,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0513625,
  'y': 0.331218,
  'z': -0.037655,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0479443,
  'y': 0.334418,
  'z': -0.0276132,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0529404,
  'y': 0.323633,
  'z': -0.0244755,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.048001,
  'y': 0.335656,
  'z': -0.0336224,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0434423,
  'y': 0.338139,
  'z': -0.0309497,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0530537,
  'y': 0.340183,
  'z': -0.0363468,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0608042,
  'y': 0.334203,
  'z': -0.0260941,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0579651,
  'y': 0.324038,
  'z': -0.0432562,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0542168,
  'y': 0.329858,
  'z': -0.0493892,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.044137,
  'y': 0.331843,
  'z': -0.0286254,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0575901,
  'y': 0.326662,
  'z': -0.0448032,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0450555,
  'y': 0.331543,
  'z': -0.0273155,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0499182,
  'y': 0.339744,
  'z': -0.0394984,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0503878,
  'y': 0.336423,
  'z': -0.0281002,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0554609,
  'y': 0.341296,
  'z': -0.0485856,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0538076,
  'y': 0.324149,
  'z': -0.0385912,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0416088,
  'y': 0.336363,
  'z': -0.0278392,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0518559,
  'y': 0.338462,
  'z': -0.0504616,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0608183,
  'y': 0.339103,
  'z': -0.041825,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0607281,
  'y': 0.342808,
  'z': -0.0529359,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0600408,
  'y': 0.343668,
  'z': -0.0570141,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0543012,
  'y': 0.328735,
  'z': -0.0463651,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0475445,
  'y': 0.332342,
  'z': -0.0309171,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0505125,
  'y': 0.328537,
  'z': -0.0223432,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0609009,
  'y': 0.331383,
  'z': -0.0378126,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0480977,
  'y': 0.331445,
  'z': -0.039573,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0608341,
  'y': 0.332479,
  'z': -0.042078,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0553219,
  'y': 0.338917,
  'z': -0.0490739,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0536013,
  'y': 0.33387,
  'z': -0.0299274,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0543791,
  'y': 0.329481,
  'z': -0.0374287,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0541998,
  'y': 0.327775,
  'z': -0.0375045,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0576037,
  'y': 0.337942,
  'z': -0.0432557,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0582143,
  'y': 0.334396,
  'z': -0.0394242,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0521922,
  'y': 0.32286,
  'z': -0.0370836,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0607514,
  'y': 0.332371,
  'z': -0.0307898,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0497705,
  'y': 0.335204,
  'z': -0.0324106,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0507895,
  'y': 0.324798,
  'z': -0.0314027,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0548816,
  'y': 0.333449,
  'z': -0.041989,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0518333,
  'y': 0.340364,
  'z': -0.0488059,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0488444,
  'y': 0.330061,
  'z': -0.0340961,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0545594,
  'y': 0.330321,
  'z': -0.0333755,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0594008,
  'y': 0.341193,
  'z': -0.0388277,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.054943,
  'y': 0.333924,
  'z': -0.0256931,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0521864,
  'y': 0.317653,
  'z': -0.0291434,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0489329,
  'y': 0.331035,
  'z': -0.0244546,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0588555,
  'y': 0.342022,
  'z': -0.0404323,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0506069,
  'y': 0.329309,
  'z': -0.0361706,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0583106,
  'y': 0.345172,
  'z': -0.0542793,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0601529,
  'y': 0.330464,
  'z': -0.0358736,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0594293,
  'y': 0.334529,
  'z': -0.0250979,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.059852,
  'y': 0.32929,
  'z': -0.0220975,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0567409,
  'y': 0.333178,
  'z': -0.0482108,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0529897,
  'y': 0.330989,
  'z': -0.0386434,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.056435,
  'y': 0.335807,
  'z': -0.0312614,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0574136,
  'y': 0.332994,
  'z': -0.0273231,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0526512,
  'y': 0.325494,
  'z': -0.030694,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0586189,
  'y': 0.337413,
  'z': -0.0450792,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0572542,
  'y': 0.341335,
  'z': -0.0538267,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0487158,
  'y': 0.334251,
  'z': -0.0290194,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0538677,
  'y': 0.333952,
  'z': -0.0461919,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0607812,
  'y': 0.332484,
  'z': -0.0419895,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0477416,
  'y': 0.327724,
  'z': -0.031563,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0544656,
  'y': 0.329391,
  'z': -0.0490636,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.055921,
  'y': 0.336821,
  'z': -0.0369108,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0626252,
  'y': 0.333812,
  'z': -0.0411363,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0537675,
  'y': 0.334899,
  'z': -0.0423321,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0507386,
  'y': 0.327385,
  'z': -0.0222386,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0579018,
  'y': 0.334991,
  'z': -0.0359681,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0593006,
  'y': 0.326212,
  'z': -0.0458337,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0548661,
  'y': 0.334045,
  'z': -0.0368886,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0459517,
  'y': 0.329382,
  'z': -0.0204638,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0590182,
  'y': 0.33585,
  'z': -0.04487,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0490934,
  'y': 0.327632,
  'z': -0.0322637,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0550269,
  'y': 0.333059,
  'z': -0.0420533,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0553625,
  'y': 0.335884,
  'z': -0.0295933,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0611933,
  'y': 0.335365,
  'z': -0.0478383,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0574456,
  'y': 0.329421,
  'z': -0.0500581,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0612438,
  'y': 0.338781,
  'z': -0.049904,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0536626,
  'y': 0.335353,
  'z': -0.0318412,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.062835,
  'y': 0.330785,
  'z': -0.0426413,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0534069,
  'y': 0.333061,
  'z': -0.0268301,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0543354,
  'y': 0.326485,
  'z': -0.0357751,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.055989,
  'y': 0.331854,
  'z': -0.0236152,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0533897,
  'y': 0.335056,
  'z': -0.027742,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 0.0582405,
  'y': 0.343324,
  'z': -0.0411273,

## Create and use `node-dist-vis` widget to display cells in 3D

In [157]:
node_dist_vis = NodeDistVis(
    nodes=node_list,
    node_target_key='Cell Type',
    node_target_value='',
    max_edge_distance=1000
)
display(node_dist_vis)

NodeDistVis(color_map=None, color_map_data=None, color_map_key=None, color_map_keys=None, edge_keys=None, edge…