## Demo of the 3D Cell Generation API

This notebook demonstrates how to get a cell type population for anatomical structures (ASpop) from HRApop, formulate a request for the 3D Cell Generation API, and display the result in 3D using the `node-dist-vis` HRA Jupyter Widgets.

In [1]:
import warnings
warnings.filterwarnings('ignore')

## Install and import libraries

In [2]:
%pip install requests pandas hra_jupyter_widgets ipywidgets

import requests
import json
from io import StringIO
import pandas as pd
from pprint import pprint

Requirement already satisfied: requests in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (2.32.5)
Requirement already satisfied: pandas in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (3.0.1)
Requirement already satisfied: hra_jupyter_widgets in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (0.4.1)
Requirement already satisfied: ipywidgets in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (8.1.8)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from requests) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from requests) (2025.10.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: anywidget in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from hra_jupyter_widgets) (0.9.21)
Requirement already satisfied: traitlets>=5.10 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from hra_jupyter_widgets) (5.14.3)
Requirement already satisfied: comm>=0.1.3 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipywidgets) (0.2.3)
Requirement already satisfied: ipython>=6.1.0 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipywidgets) (9.6.0)
Requirement already satisfied: widgetsnbextension~=4.0.14 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from ipywidgets) (4.0.15)
Requirement already satisfied: jupyterlab_widgets~=3.0.15 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from ipywidgets) (3.0.16)
Requirement already satisfied: colorama in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.4.6)
Requirement already satisfied: decorator in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (5.2.1)
Requirement already satisfied: ipython-pygments-lexers in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (1.1.1)
Requirement already satisfied: jedi>=0.16 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.19.2)
Requirement already satisfied: matplotlib-inline in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.1.7)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (3.0.52)
Requirement already satisfied: pygments>=2.4.0 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (2.19.2)
Requirement already satisfied: stack_data in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from ipython>=6.1.0->ipywidgets) (0.6.3)
Requirement already satisfied: six>=1.5 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: psygnal>=0.8.1 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from anywidget->hra_jupyter_widgets) (0.15.1)
Requirement already satisfied: typing-extensions>=4.2.0 in c:\users\abueckle\appdata\local\programs\python\python312\lib\site-packages (from anywidget->hra_jupyter_widgets) (4.15.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from jedi>=0.16->ipython>=6.1.0->ipywidgets) (0.8.5)
Requirement already satisfied: wcwidth in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=6.1.0->ipywidgets) (0.2.14)
Requirement already satisfied: executing>=1.2.0 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (3.0.0)
Requirement already satisfied: pure-eval in c:\users\abueckle\appdata\roaming\python\python312\site-packages (from stack_data->ipython>=6.1.0->ipywidgets) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## Import widgets

In [3]:
import ipywidgets as widgets
from hra_jupyter_widgets import (
    NodeDistVis,  # VCCF 3D Node Distance Visualization
    CdeVisualization,
)

## Exemplary call to visualize cell type population for the renal pyramid A in the male, left kidney

In [4]:
# get ASpop for the male, left kidney
response = requests.get('https://apps.humanatlas.io/api/grlc/hra-pop/cell_types_in_anatomical_structurescts_per_as.csv', headers = {'accept':'text/csv'})
df_as_pop = pd.read_csv(StringIO(response.text))
df_as_pop

,organ,organ_id,as,as_label,sex,tool,modality,cell_id,cell_label,cell_count,cell_percentage,dataset_count
0,large intestine,http://purl.obolibrary.org/obo/UBERON_0000059,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_colonocyte,Colonocyte,1.205,0.147653,3
1,large intestine,http://purl.obolibrary.org/obo/UBERON_0000059,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_iga-plasma-cell,IgA plasma cell,1.182,0.144835,3
2,large intestine,http://purl.obolibrary.org/obo/UBERON_0000059,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_best4-epithelial,BEST4+ epithelial,0.699,0.085651,3
3,large intestine,http://purl.obolibrary.org/obo/UBERON_0000059,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_activated-cd4-t,Activated CD4 T,0.690,0.084548,3
4,large intestine,http://purl.obolibrary.org/obo/UBERON_0000059,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_ta,TA,0.540,0.066168,3
...,...,...,...,...,...,...,...,...,...,...,...,...
8891,lung,http://purl.obolibrary.org/obo/UBERON_0001004,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_0000097,Mast Cell,15322.464,0.024702,1
8892,lung,http://purl.obolibrary.org/obo/UBERON_0001004,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_4033039,CD8+ T Cell,3691.176,0.005951,1
8893,lung,http://purl.obolibrary.org/obo/UBERON_0001004,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,https://purl.org/ccf/ASCTB-TEMP_lymphatic-endo...,Lymphatic Endothelial (and some immune cells),1753.956,0.002828,1
8894,lung,http://purl.obolibrary.org/obo/UBERON_0001004,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,https://purl.org/ccf/ASCTB-TEMP_basal-epitheli...,Basal Epithelial Cell,970.104,0.001564,1
8895,lung,http://purl.obolibrary.org/obo/UBERON_0001004,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_0000236,B Cell,462.144,0.000745,1

In [5]:
# subset to only keep male left kidney, renal pyramid, azimuth
df_renal_pyramid = df_as_pop[(df_as_pop['organ'] == 'Left kidney')& (df_as_pop['as_label'] == 'renal pyramid') & (df_as_pop['tool'] == 'azimuth') & (df_as_pop['sex']=='Male')]
df_renal_pyramid

,organ,organ_id,as,as_label,sex,tool,modality,cell_id,cell_label,cell_count,cell_percentage,dataset_count
6055,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001109,Cortical Thick Ascending Limb,105493.791,0.228450,31
6057,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030012,Descending Thin Limb Type 1,48210.290,0.104401,31
6059,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000714,Cortical Collecting Duct Principal,47365.703,0.102572,31
6061,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001108,Medullary Thick Ascending Limb,37587.100,0.081396,31
6063,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000768,Connecting Tubule,36564.115,0.079181,31
6065,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001107,Ascending Thin Limb,28549.937,0.061826,31
6067,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030022,Medullary Fibroblast,28149.594,0.060959,31
6069,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030016,Distal Convoluted Tubule Type 1,21950.691,0.047535,31
6071,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_descending-vas...,Descending Vasa Recta Endothelial,19436.637,0.042091,31
6072,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000718,Inner Medullary Collecting Duct,13973.404,0.030260,31
6075,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030014,Descending Thin Limb Type 3,9374.074,0.020300,31
6076,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000692,Fibroblast,7688.019,0.016649,31
6078,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0002201,Intercalated Type B,6841.483,0.014815,31
6081,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000850,Macula Densa,6573.065,0.014234,31
6083,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001131,Ascending Vasa Recta Endothelial,6114.286,0.013241,31
6085,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030013,Descending Thin Limb Type 2,6053.296,0.013109,31
6087,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000716,Outer Medullary Collecting Duct Principal,3460.530,0.007494,31
6088,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001318,Vascular Smooth Muscle / Pericyte,3008.679,0.006515,31
6091,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000717,Outer Medullary Collecting Duct Intercalated T...,2971.651,0.006435,31
6092,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0011031,Monocyte-derived,2951.421,0.006391,31
6095,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_peritubular-ca...,Peritubular Capilary Endothelial,2368.401,0.005129,31
6096,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000084,T,2249.235,0.004871,31
6099,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030009,Proximal Tubule Epithelial Segment 1,2203.518,0.004772,31
6101,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000452,Parietal Epithelial,2146.141,0.004648,31
6103,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030018,Connecting Tubule Principal,1745.379,0.003780,31
6105,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000890,M2 Macrophage,1463.011,0.003168,31
6107,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000715,Cortical Collecting Duct Intercalated Type A,1426.233,0.003089,31
6108,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001005,Glomerular Capillary Endothelial,1368.161,0.002963,31
6111,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000597,Papillary Tip Epithelial,1084.013,0.002347,31
6113,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000653,Podocyte,1047.483,0.002268,31
6115,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030011,Proximal Tubule Epithelial Segment 3,636.392,0.001378,31
6116,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000412,Afferent / Efferent Arteriole Endothelial,468.172,0.001014,31
6118,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000650,Mesangial,432.708,0.000937,31
6121,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000990,Classical Dendritic,358.000,0.000775,31
6123,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000236,B,152.012,0.000329,31
6125,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030010,Proximal Tubule Epithelial Segment 2,114.691,0.000248,31
6126,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030017,Distal Convoluted Tubule Type 2,38.735,0.000084,31
6129,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000648,Renin-positive Juxtaglomerular Granular,38.547,0.000083,31
6130,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0002138,Lymphatic Endothelial,34.004,0.000074,31
6133,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000097,Mast,34.000,0.000074,31
6135,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000814,Natural Killer T,14.589,0.000032,31
6137,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0002573,Schwann / Neural,13.858,0.000030,31
6139,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000786,Plasma,6.012,0.000013,31
6141,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000775,Neutrophil,6.000,0.000013,31
6143,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030020,Connecting Tubule Intercalated Type A,5.000,0.000011,31
6144,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_0000875,Non-classical monocyte,4.027,0.000009,31
6147,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4033078,Cycling Mononuclear Phagocyte,4.000,0.000009,31

In [6]:
# filter out cells below threshold such that only n_max CTs remain
n_max = 10

top10 = df_renal_pyramid.nlargest(n_max, "cell_percentage")
top10

,organ,organ_id,as,as_label,sex,tool,modality,cell_id,cell_label,cell_count,cell_percentage,dataset_count
6055,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001109,Cortical Thick Ascending Limb,105493.791,0.228450,31
6057,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030012,Descending Thin Limb Type 1,48210.290,0.104401,31
6059,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000714,Cortical Collecting Duct Principal,47365.703,0.102572,31
6061,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001108,Medullary Thick Ascending Limb,37587.100,0.081396,31
6063,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000768,Connecting Tubule,36564.115,0.079181,31
6065,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1001107,Ascending Thin Limb,28549.937,0.061826,31
6067,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030022,Medullary Fibroblast,28149.594,0.060959,31
6069,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_4030016,Distal Convoluted Tubule Type 1,21950.691,0.047535,31
6071,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_descending-vas...,Descending Vasa Recta Endothelial,19436.637,0.042091,31
6072,Left kidney,http://purl.obolibrary.org/obo/UBERON_0004538,http://purl.obolibrary.org/obo/UBERON_0004200,renal pyramid,Male,azimuth,sc_transcriptomics,http://purl.obolibrary.org/obo/CL_1000718,Inner Medullary Collecting Duct,13973.404,0.030260,31

In [7]:
# transform into dict so it can be used in the payload for the API request

In [8]:
node_distribution = dict(zip(top10['cell_label'], top10['cell_percentage']))
pprint(node_distribution)

{'Ascending Thin Limb': 0.06182582952775565,
 'Connecting Tubule': 0.07918079611955897,
 'Cortical Collecting Duct Principal': 0.1025719909343514,
 'Cortical Thick Ascending Limb': 0.2284502812949354,
 'Descending Thin Limb Type 1': 0.1044009719189105,
 'Descending Vasa Recta Endothelial ': 0.04209067801988033,
 'Distal Convoluted Tubule Type 1': 0.04753494481555039,
 'Inner Medullary Collecting Duct': 0.03025986690010765,
 'Medullary Fibroblast': 0.06095887356667489,
 'Medullary Thick Ascending Limb': 0.08139610385279325}

In [9]:
def call_3d_cell_api(file: str, scene_node: str, num_nodes: int, node_distribution: dict):
  """Wrapper function to make a call to the 3D Cell Generation API using a payload constructed with user-provided arguments

  Args:
      file (str): the link to the GLB file of the organ, see, e.g., https://apps.humanatlas.io/api#get-/v1/reference-organs
      scene_node (str): the scene node of the AS
      num_nodes (int): the max. total number of cells
      node_distribution (dict): a dict with key-value-pairs for cell label and percentages [0,1]
  """

  url = 'https://apps.humanatlas.io/api/v1/mesh-3d-cell-population'

  payload = {
      'file': file,
      'file_subpath': scene_node,
      'num_nodes': num_nodes,
      'node_distribution': node_distribution
  }

  headers = {
      'Content-Type': 'application/json'
  }

  try:
      response = requests.post(url, data=json.dumps(payload), headers=headers)
      response.raise_for_status()  # Raise an exception for HTTP errors (4xx or 5xx)
      return pd.read_csv(StringIO(response.text))
      print("Response Status Code:", response.status_code)
      print("Response JSON:", response.json())
  except requests.exceptions.RequestException as e:
      print(f"An error occurred: {e}")
      return None

In [10]:
# make request
result = call_3d_cell_api(
    file='https://cdn.humanatlas.io/digital-objects/ref-organ/kidney-male-left/v1.3/assets/3d-vh-m-kidney-l.glb',
    scene_node='VH_M_renal_pyramid_L_a',
    num_nodes=10000,
    node_distribution=node_distribution
)
result

             x         y         z                        Cell Type
0     0.052403  0.333208 -0.032828    Cortical Thick Ascending Limb
1     0.058614  0.333871 -0.040892    Cortical Thick Ascending Limb
2     0.063290  0.333559 -0.039525    Cortical Thick Ascending Limb
3     0.056867  0.334292 -0.032555    Cortical Thick Ascending Limb
4     0.048743  0.331199 -0.035920    Cortical Thick Ascending Limb
...        ...       ...       ...                              ...
8376  0.053853  0.335280 -0.038417  Inner Medullary Collecting Duct
8377  0.055511  0.334964 -0.029081  Inner Medullary Collecting Duct
8378  0.046584  0.327578 -0.020346  Inner Medullary Collecting Duct
8379  0.054107  0.326008 -0.030708  Inner Medullary Collecting Duct
8380  0.056943  0.337244 -0.029277  Inner Medullary Collecting Duct

[8381 rows x 4 columns]

In [11]:
# increase scale
temp_result = result
result[["x", "y", "z"]] = result[["x", "y", "z"]].apply(lambda v: v * 1000000)
result = temp_result

In [12]:
# Next, let's define a function that turns a DataFrame into a node list that can then be passed into the CdeVisualization or NodeDistVis widget
def make_node_list(df: pd.DataFrame, is_3d: bool = False):
    """Turn a DataFrame into a list of dicts for passing them into a HRA widget

    Args:
        df (pd.DataFrame): A DataFrame with cells
    """

    # If the df does not have a z-axis column, let's add one and set all cells to 0
    if not is_3d:
        df.loc[:, ("z")] = 0

    node_list = [
        {"x": row["x"], "y": row["y"], "z": row["z"], "Cell Type": row["Cell Type"]}
        for index, row in df.iterrows()
    ]

    return node_list

In [13]:
node_list = make_node_list(result, True)
node_list

[{'x': 52403.5,
  'y': 333208.0,
  'z': -32827.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58613.8,
  'y': 333871.0,
  'z': -40891.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 63290.200000000004,
  'y': 333559.0,
  'z': -39524.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56867.3,
  'y': 334292.0,
  'z': -32554.600000000002,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48743.0,
  'y': 331199.0,
  'z': -35920.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48368.5,
  'y': 326349.0,
  'z': -31831.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56529.799999999996,
  'y': 331748.0,
  'z': -46189.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52729.6,
  'y': 334915.0,
  'z': -28705.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45613.0,
  'y': 335807.0,
  'z': -40831.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54621.6,
  'y': 338678.0,
  'z': -38276.200000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52385.6,
  'y': 326100.0,
  'z': -32273.999999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53854.600000000006,
  'y': 334903.0,
  'z': -36959.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52234.1,
  'y': 330044.0,
  'z': -35752.600000000006,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55099.799999999996,
  'y': 327212.0,
  'z': -49040.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55199.2,
  'y': 332344.0,
  'z': -50356.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49875.4,
  'y': 340649.0,
  'z': -36793.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 46143.200000000004,
  'y': 327518.0,
  'z': -22545.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56482.9,
  'y': 345246.0,
  'z': -54242.899999999994,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51765.899999999994,
  'y': 337116.0,
  'z': -48182.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60469.1,
  'y': 331418.0,
  'z': -33457.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52194.8,
  'y': 319812.0,
  'z': -35441.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59803.4,
  'y': 327613.0,
  'z': -36437.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54282.4,
  'y': 329920.0,
  'z': -27659.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48065.700000000004,
  'y': 329923.0,
  'z': -28226.100000000002,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57757.799999999996,
  'y': 329438.0,
  'z': -33781.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49514.299999999996,
  'y': 324849.0,
  'z': -26459.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48907.600000000006,
  'y': 332102.0,
  'z': -27558.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49608.899999999994,
  'y': 335700.0,
  'z': -28263.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 61438.3,
  'y': 332885.0,
  'z': -33464.4,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56101.5,
  'y': 330261.0,
  'z': -46941.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58660.299999999996,
  'y': 341772.0,
  'z': -49234.600000000006,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60155.5,
  'y': 342100.0,
  'z': -50307.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 46411.3,
  'y': 329666.0,
  'z': -20964.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45694.5,
  'y': 326387.0,
  'z': -22371.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45414.9,
  'y': 332554.0,
  'z': -37204.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54533.3,
  'y': 345492.0,
  'z': -45817.299999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 43481.5,
  'y': 332732.0,
  'z': -29827.699999999997,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58678.0,
  'y': 332835.0,
  'z': -25227.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 44546.0,
  'y': 330298.0,
  'z': -24600.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52734.0,
  'y': 326661.0,
  'z': -33974.299999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52543.2,
  'y': 340378.0,
  'z': -36339.799999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49444.1,
  'y': 330094.0,
  'z': -22636.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58004.100000000006,
  'y': 330366.0,
  'z': -25468.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54553.0,
  'y': 336964.0,
  'z': -39635.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50559.399999999994,
  'y': 328727.0,
  'z': -34947.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49028.299999999996,
  'y': 329077.0,
  'z': -37568.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52893.4,
  'y': 325445.0,
  'z': -31421.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57767.7,
  'y': 342180.0,
  'z': -49565.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48326.2,
  'y': 332843.0,
  'z': -30561.899999999998,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58958.799999999996,
  'y': 329367.0,
  'z': -31852.900000000005,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55902.100000000006,
  'y': 335970.0,
  'z': -27949.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48315.9,
  'y': 331316.0,
  'z': -28326.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52789.4,
  'y': 327953.0,
  'z': -29980.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53762.1,
  'y': 335545.0,
  'z': -48975.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 61477.0,
  'y': 332455.0,
  'z': -43282.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55691.5,
  'y': 327032.0,
  'z': -32835.4,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59597.9,
  'y': 329650.0,
  'z': -22818.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49138.9,
  'y': 323368.0,
  'z': -35120.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55280.6,
  'y': 330060.0,
  'z': -45825.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51934.1,
  'y': 342994.0,
  'z': -38178.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54636.1,
  'y': 335332.0,
  'z': -38198.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59554.6,
  'y': 338025.0,
  'z': -52940.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58949.4,
  'y': 345563.0,
  'z': -57663.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48589.2,
  'y': 323589.0,
  'z': -21976.699999999997,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51085.899999999994,
  'y': 330055.0,
  'z': -30331.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55805.6,
  'y': 331510.0,
  'z': -51371.600000000006,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56518.8,
  'y': 332288.0,
  'z': -52427.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55470.5,
  'y': 333229.0,
  'z': -38570.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53709.9,
  'y': 331962.0,
  'z': -32181.300000000003,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48235.7,
  'y': 328771.0,
  'z': -35626.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59246.0,
  'y': 328618.0,
  'z': -21802.100000000002,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53928.1,
  'y': 338470.0,
  'z': -30821.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 44571.3,
  'y': 334994.0,
  'z': -38575.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60492.6,
  'y': 335611.0,
  'z': -42820.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58070.1,
  'y': 329234.0,
  'z': -42678.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59495.1,
  'y': 340007.0,
  'z': -37946.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52481.8,
  'y': 326746.0,
  'z': -26953.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53659.7,
  'y': 339719.0,
  'z': -42874.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49123.5,
  'y': 339128.0,
  'z': -35771.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56704.7,
  'y': 332423.0,
  'z': -40139.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 43414.5,
  'y': 328713.0,
  'z': -21592.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59507.299999999996,
  'y': 341640.0,
  'z': -41077.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60844.700000000004,
  'y': 336585.0,
  'z': -38852.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55525.6,
  'y': 334719.0,
  'z': -30608.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58336.3,
  'y': 333196.0,
  'z': -34228.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 47289.3,
  'y': 341654.0,
  'z': -37821.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 47233.0,
  'y': 336404.0,
  'z': -39402.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50569.799999999996,
  'y': 321818.0,
  'z': -31831.100000000002,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55449.4,
  'y': 330984.0,
  'z': -33157.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52041.0,
  'y': 342030.0,
  'z': -51363.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58577.700000000004,
  'y': 338051.0,
  'z': -41908.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45671.9,
  'y': 336222.0,
  'z': -39115.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49370.299999999996,
  'y': 332771.0,
  'z': -32777.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59001.4,
  'y': 329633.0,
  'z': -43450.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59505.200000000004,
  'y': 340682.0,
  'z': -43047.799999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59892.9,
  'y': 334126.0,
  'z': -48789.399999999994,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49946.1,
  'y': 326432.0,
  'z': -31698.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53924.399999999994,
  'y': 327313.0,
  'z': -30755.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52755.200000000004,
  'y': 334699.0,
  'z': -46974.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51045.399999999994,
  'y': 339484.0,
  'z': -33659.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50992.299999999996,
  'y': 344824.0,
  'z': -41888.4,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45706.799999999996,
  'y': 330141.0,
  'z': -35073.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56822.4,
  'y': 332816.0,
  'z': -45770.4,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60266.3,
  'y': 334546.0,
  'z': -30671.4,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56702.1,
  'y': 336456.0,
  'z': -46913.200000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52287.9,
  'y': 335879.0,
  'z': -46992.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56719.8,
  'y': 342429.0,
  'z': -54406.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 62827.3,
  'y': 327837.0,
  'z': -39186.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52014.8,
  'y': 336204.0,
  'z': -40210.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53575.0,
  'y': 333673.0,
  'z': -38412.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53327.100000000006,
  'y': 327133.0,
  'z': -34881.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60936.4,
  'y': 331171.0,
  'z': -26768.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 46293.1,
  'y': 335610.0,
  'z': -37878.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 46742.5,
  'y': 334394.0,
  'z': -36134.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 47291.0,
  'y': 333538.0,
  'z': -32528.500000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54902.0,
  'y': 324155.0,
  'z': -46031.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60715.3,
  'y': 342122.0,
  'z': -53546.200000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54121.0,
  'y': 334767.0,
  'z': -42565.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54356.799999999996,
  'y': 340690.0,
  'z': -41942.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51872.9,
  'y': 340706.0,
  'z': -49290.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 52233.0,
  'y': 333008.0,
  'z': -35473.4,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57771.4,
  'y': 337077.0,
  'z': -28644.800000000003,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49498.6,
  'y': 336332.0,
  'z': -30963.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50888.6,
  'y': 337128.0,
  'z': -30000.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54610.4,
  'y': 336491.0,
  'z': -33080.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 61459.2,
  'y': 331883.0,
  'z': -25793.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48595.3,
  'y': 332142.0,
  'z': -28756.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60924.7,
  'y': 332822.0,
  'z': -41221.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49411.9,
  'y': 332062.0,
  'z': -28296.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53080.799999999996,
  'y': 327275.0,
  'z': -24391.800000000003,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59269.1,
  'y': 339106.0,
  'z': -43084.299999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53912.1,
  'y': 345602.0,
  'z': -43588.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60826.5,
  'y': 340323.0,
  'z': -39637.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57369.5,
  'y': 338733.0,
  'z': -39105.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45391.5,
  'y': 333570.0,
  'z': -37988.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48309.8,
  'y': 326743.0,
  'z': -24447.199999999997,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59624.700000000004,
  'y': 337322.0,
  'z': -45377.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56886.1,
  'y': 330211.0,
  'z': -50058.2,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54212.1,
  'y': 328181.0,
  'z': -29128.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 62021.0,
  'y': 327374.0,
  'z': -40919.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51789.0,
  'y': 328445.0,
  'z': -30763.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49028.0,
  'y': 331300.0,
  'z': -32222.899999999998,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49168.4,
  'y': 326000.0,
  'z': -20763.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 53835.5,
  'y': 339969.0,
  'z': -37104.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58967.7,
  'y': 327453.0,
  'z': -24451.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56121.299999999996,
  'y': 327369.0,
  'z': -50939.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 44234.1,
  'y': 335987.0,
  'z': -29946.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51358.5,
  'y': 324364.0,
  'z': -27141.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56225.4,
  'y': 331010.0,
  'z': -25988.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 47194.399999999994,
  'y': 325520.0,
  'z': -25082.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56728.5,
  'y': 330135.0,
  'z': -39164.299999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50363.8,
  'y': 336512.0,
  'z': -30076.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57246.6,
  'y': 331089.0,
  'z': -47577.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58318.2,
  'y': 330859.0,
  'z': -50292.299999999996,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45425.399999999994,
  'y': 325268.0,
  'z': -24247.100000000002,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50060.6,
  'y': 328583.0,
  'z': -22239.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59292.299999999996,
  'y': 334858.0,
  'z': -48912.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57045.5,
  'y': 333496.0,
  'z': -26059.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 43272.5,
  'y': 336907.0,
  'z': -27755.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58910.299999999996,
  'y': 330956.0,
  'z': -36722.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56986.5,
  'y': 331217.0,
  'z': -45404.600000000006,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51309.7,
  'y': 337966.0,
  'z': -35009.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45500.899999999994,
  'y': 328207.0,
  'z': -20768.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 54800.4,
  'y': 333662.0,
  'z': -41833.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57766.1,
  'y': 328182.0,
  'z': -43852.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55896.9,
  'y': 334288.0,
  'z': -36437.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59329.3,
  'y': 327656.0,
  'z': -36711.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45048.8,
  'y': 327619.0,
  'z': -21467.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58695.9,
  'y': 329836.0,
  'z': -30024.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 47115.4,
  'y': 335017.0,
  'z': -40521.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 56347.9,
  'y': 336956.0,
  'z': -29685.0,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58958.799999999996,
  'y': 331634.0,
  'z': -32513.100000000002,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57865.600000000006,
  'y': 334497.0,
  'z': -46271.399999999994,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50006.0,
  'y': 332322.0,
  'z': -40848.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49336.9,
  'y': 333877.0,
  'z': -27121.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51254.9,
  'y': 333461.0,
  'z': -34203.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 46927.700000000004,
  'y': 327323.0,
  'z': -24388.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 46001.9,
  'y': 328004.0,
  'z': -25609.7,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50303.4,
  'y': 334165.0,
  'z': -42555.9,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55576.2,
  'y': 331165.0,
  'z': -37116.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 45501.2,
  'y': 330963.0,
  'z': -25579.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55033.7,
  'y': 339898.0,
  'z': -37113.3,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60025.700000000004,
  'y': 330416.0,
  'z': -39619.4,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 58168.0,
  'y': 329456.0,
  'z': -32716.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 48616.2,
  'y': 329049.0,
  'z': -38042.600000000006,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55313.6,
  'y': 345998.0,
  'z': -44150.700000000004,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 57449.9,
  'y': 328485.0,
  'z': -34763.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 49797.2,
  'y': 335226.0,
  'z': -29717.6,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 50113.4,
  'y': 331333.0,
  'z': -29091.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 59896.3,
  'y': 329014.0,
  'z': -44320.1,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 55352.6,
  'y': 332852.0,
  'z': -51405.8,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 51460.1,
  'y': 332684.0,
  'z': -40406.5,
  'Cell Type': 'Cortical Thick Ascending Limb'},
 {'x': 60124.6,
  'y': 332296.0,

## Create and use `node-dist-vis` widget to display cells in 3D

In [14]:
vis = CdeVisualization(
    nodes=node_list,
    node_target_key='Cell Type',
    node_target_value='',
    max_edge_distance=10000000000000
)
display(vis)