## Code to query, visualize, and use output from the HRA Workflow Runner downstream

In [1]:
%pip install duckdb pandas

Collecting duckdb
  Downloading duckdb-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (966 bytes)
Requirement already satisfied: pandas in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (2.2.3)
Requirement already satisfied: numpy>=1.22.4 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2.2.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/abueckle/Github/hra-pop-notebooks/.venv/lib/python3.10/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading duckdb-1.2.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (20.2 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.2/20.2 MB 78.1 MB/s eta 0:00:00:00:01
Installing collected packages: duckdb
Successfully installed duckdb-1.2.2

[notice] A new release of pip is available: 25.1 -> 25.1.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [20]:
# Combine cell instances and normalize columns for analysis

import duckdb

data_dir = "data/gtex"
query = f"""
SELECT
  split_part(filename, '/', 3) as dataset,
  Organ_ID as organ,
  split_part(filename, '/', 4) as tool,
  column00 as cell,
  clid as cell_id,
  CL_Label as cell_label,
  match_type,
  COALESCE("mapping.score", conf_score, popv_prediction_score / 6, 0) as confidence_score,
FROM read_csv('
{ data_dir }/*/*/annotations.csv', 
union_by_name = true, 
filename = true, 
ignore_errors=true,
quote='"')
"""

cells = duckdb.sql(query)
cells.write_csv(f'{ data_dir }/cell-instances.csv.gz')
cells.show()

┌───────────────────────────────┬────────────────┬─────────┬─────────────────────────────────┬────────────┬─────────────────────────────────────┬─────────────────┬────────────────────┐
│            dataset            │     organ      │  tool   │              cell               │  cell_id   │             cell_label              │   match_type    │  confidence_score  │
│            varchar            │    varchar     │ varchar │             varchar             │  varchar   │               varchar               │     varchar     │       double       │
├───────────────────────────────┼────────────────┼─────────┼─────────────────────────────────┼────────────┼─────────────────────────────────────┼─────────────────┼────────────────────┤
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TATGCCCGTTCTGAAC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_AGATTGCCATGGGACA-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                0.5 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TTGACTTGTACACCGC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_CACTCCATCTGGAGCC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │ 0.8333333333333334 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_GTGCTTCAGTGAATTG-prostate │ CL:0000192 │ smooth muscle cell                  │ skos:exactMatch │ 0.8333333333333334 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_CACACAAAGCAAATCA-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_CTGGTCTAGTGCGTGA-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TCGTAGATCACCACCT-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TAGTGGTCATCTCGCT-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-12BJ1-5007-SM-H8L6U │ UBERON:0002367 │ popv    │ CST04_TAAGAGAAGACAGACC-prostate │ CL:0002340 │ luminal cell of prostate epithelium │ skos:exactMatch │ 0.6666666666666666 │
│               ·               │       ·        │  ·      │              ·                  │     ·      │             ·                       │        ·        │          ·         │
│               ·               │       ·        │  ·      │              ·                  │     ·      │             ·                       │        ·        │          ·         │
│               ·               │       ·        │  ·      │              ·                  │     ·      │             ·                       │        ·        │          ·         │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CTAGAGTTCTGCTTGC-heart    │ CL:1000413 │ endothelial cell of artery          │ skos:exactMatch │  0.892433202610579 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CGCGGTAAGTTCGATC-heart    │ CL:0000623 │ natural killer cell                 │ skos:exactMatch │ 0.7439126027805105 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_ATTGGTGCACAGGCCT-heart    │ CL:0002131 │ regular ventricular cardiac myocyte │ skos:exactMatch │ 0.7464198444613545 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_AACTCAGTCGAATGCT-heart    │ CL:0002573 │ Schwann cell                        │ skos:exactMatch │                1.0 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CAGCAGCTCATACGGT-heart    │ CL:0000623 │ natural killer cell                 │ skos:exactMatch │ 0.9551184274168342 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_TCGCGTTGTCAAAGCG-heart    │ CL:0000235 │ macrophage                          │ skos:exactMatch │ 0.7239919774274294 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_AACTCCCAGAAGGACA-heart    │ CL:1000413 │ endothelial cell of artery          │ skos:exactMatch │ 0.8159056018243378 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_CAGAATCGTATAGGGC-heart    │ CL:1000414 │ endothelial cell of venule          │ skos:exactMatch │ 0.8441983392960823 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_AGCGTCGTCCGTTGTC-heart    │ CL:1000414 │ endothelial cell of venule          │ skos:exactMatch │ 0.9293715391424932 │
│ GTEX-GTEX-13N11-5002-SM-H5JDV │ UBERON:0000948 │ azimuth │ CST02_GCGGGTTCAATGGAGC-heart    │ CL:0000057 │ fibroblast                          │ skos:exactMatch │ 0.8572748811180838 │
├───────────────────────────────┴────────────────┴─────────┴─────────────────────────────────┴────────────┴─────────────────────────────────────┴─────────────────┴────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                              8 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [21]:
# Show only cells annotated with azimuth
cells.filter("tool = 'azimuth'")

┌───────────────────────────────┬──────────────────────┬─────────┬─────────────────────────────┬────────────────────┬────────────┬──────────────────────┬────────────────────┐
│            dataset            │        organ         │  tool   │            cell             │      cell_id       │ cell_label │      match_type      │  confidence_score  │
│            varchar            │       varchar        │ varchar │           varchar           │      varchar       │  varchar   │       varchar        │       double       │
├───────────────────────────────┼──────────────────────┼─────────┼─────────────────────────────┼────────────────────┼────────────┼──────────────────────┼────────────────────┤
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_TCTTTCCTCTGCTTGC-lung │ 0.935159738908882  │ None       │ AT2                  │ 1.0000000000000002 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_TCGTACCGTCAGCTAT-lung │ 0.9262700597571508 │ None       │ AT2                  │ 0.9825864029578535 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_ATTATCCAGGCCCGTT-lung │ 0.9345360959522296 │ None       │ AT2                  │ 0.9345360959522296 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_GCGCAGTAGCTACCGC-lung │ 0.9128188406475647 │ None       │ AT2                  │                1.0 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_ATCATCTAGTCACGCC-lung │ 0.9475832161057612 │ None       │ AT2                  │ 0.9999999999999997 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_CACACAACATGAAGTA-lung │ 0.8582850062951333 │ None       │ AT2                  │ 0.8582850062951333 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_GACTACAGTTAAAGTG-lung │ 0.4820470099565222 │ None       │ AT1                  │ 0.4928594965441799 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_CCGGGATCAAACTGCT-lung │ 0.9592909813659262 │ None       │ AT2                  │ 0.9999999999999999 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_TTGACTTTCTTCAACT-lung │ 0.9084187977120182 │ None       │ AT2                  │ 0.9084187977120182 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ CST03_CTCAGAATCGTAGGAG-lung │ 0.9544784883254089 │ None       │ AT2                  │                1.0 │
│               ·               │  ·                   │    ·    │              ·              │         ·          │  ·         │  ·                   │                 ·  │
│               ·               │  ·                   │    ·    │              ·              │         ·          │  ·         │  ·                   │                 ·  │
│               ·               │  ·                   │    ·    │              ·              │         ·          │  ·         │  ·                   │                 ·  │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_CTCACACTCGAATGCT-lung │ 0.9279843328253786 │ None       │ AT2                  │ 0.9279843328253786 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ Alveolar macrophages │ azimuth │ TST03_AAAGTAGGTCTAGTGT-lung │ 0.5181625504339988 │ None       │ Alveolar macrophages │   0.96494704058258 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_TGTCCCATCGTATCAG-lung │ 0.8509238872255773 │ None       │ AT1                  │ 0.8509238872255773 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_GATGAGGGTCCGACGT-lung │ 0.8193687307731168 │ None       │ AT2                  │ 0.8404955616725349 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_CCTATTATCGGCGGTT-lung │ 1.0000000000000002 │ None       │ AT1                  │ 1.0000000000000002 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_ATCATCTTCGGGAGTA-lung │ 0.7865978902490603 │ None       │ AT2                  │ 0.7865978902490603 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ Alveolar macrophages │ azimuth │ TST03_TATCTCAGTTCGCGAC-lung │ 0.5550881118758979 │ None       │ Alveolar macrophages │ 0.9208195915864432 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_GGCCGATAGGATCGCA-lung │ 0.9999999999999998 │ None       │ AT1                  │ 0.9999999999999998 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_TGTCCCAAGAATTCCC-lung │ 1.0                │ None       │ AT1                  │                1.0 │
│ GTEX-GTEX-13N11-5030-SM-H5JDW │ None                 │ azimuth │ TST03_CATCGGGTCGCCTGAG-lung │ 1.0000000000000002 │ None       │ AT2                  │ 1.0000000000000002 │
├───────────────────────────────┴──────────────────────┴─────────┴─────────────────────────────┴────────────────────┴────────────┴──────────────────────┴────────────────────┤
│ ? rows (>9999 rows, 20 shown)                                                                                                                                    8 columns │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [22]:

# Cell summary of all cells (counted 3x because run with 3 annotation tools)
cells.aggregate("cell_id, first(cell_label) as cell_label, count(cell) as cell_count").order("cell_count DESC")

┌───────────────────────────────────────────┬──────────────────────────────────────────┬────────────┐
│                  cell_id                  │                cell_label                │ cell_count │
│                  varchar                  │                 varchar                  │   int64    │
├───────────────────────────────────────────┼──────────────────────────────────────────┼────────────┤
│ CL:0002063                                │ type II pneumocyte                       │      27364 │
│ CL:0000235                                │ macrophage                               │      22554 │
│ CL:0002131                                │ regular ventricular cardiac myocyte      │      21780 │
│ CL:0000057                                │ fibroblast                               │      18672 │
│ CL:0002062                                │ type I pneumocyte                        │      14423 │
│ CL:0000746                                │ cardiac muscle cell                      │      11286 │
│ CL:0000192                                │ smooth muscle cell                       │       8898 │
│ CL:0002326                                │ luminal epithelial cell of mammary gland │       8815 │
│ CL:0002153                                │ corneocyte                               │       8188 │
│ CL:0002548                                │ fibroblast of cardiac tissue             │       6903 │
│     ·                                     │           ·                              │          · │
│     ·                                     │           ·                              │          · │
│     ·                                     │           ·                              │          · │
│ CL:4023054                                │ mesothelial fibroblast                   │          3 │
│ CL:0002072                                │ nodal myocyte                            │          2 │
│ CL:0000037                                │ hematopoietic stem cell                  │          2 │
│ CL:0000784                                │ plasmacytoid dendritic cell              │          2 │
│ CL:0000545                                │ T-helper 1 cell                          │          2 │
│ CL:0000899                                │ T-helper 17 cell                         │          1 │
│ CL:0000546                                │ T-helper 2 cell                          │          1 │
│ ASCTB-TEMP:cd8-positive-alpha-beta-t-cell │ CD8-positive, alpha-beta T cell          │          1 │
│ CL:0000038                                │ erythroid progenitor cell                │          1 │
│ CL:0001058                                │ plasmacytoid dendritic cell, human       │          1 │
├───────────────────────────────────────────┴──────────────────────────────────────────┴────────────┤
│ 139 rows (20 shown)                                                                     3 columns │
└───────────────────────────────────────────────────────────────────────────────────────────────────┘

In [37]:
# Cell summaries by tool
summaries = cells.aggregate("tool, cell_id, first(cell_label) as cell_label, count(cell) as cell_count").order("tool, cell_count DESC")
df = summaries.to_df()
df

,tool,cell_id,cell_label,cell_count
0,azimuth,CL:0002131,regular ventricular cardiac myocyte,15017
1,azimuth,CL:0002063,type II pneumocyte,9000
2,azimuth,CL:0000057,fibroblast,8342
3,azimuth,CL:0011031,monocyte-derived dendritic cell,6212
4,azimuth,CL:0002062,type I pneumocyte,5513
...,...,...,...,...
204,popv,CL:4028006,alveolar type 2 fibroblast cell,3
205,popv,CL:0000794,"CD8-positive, alpha-beta cytotoxic T cell",2
206,popv,CL:0002394,CD141-positive myeloid dendritic cell,1
207,popv,ASCTB-TEMP:cd8-positive-alpha-beta-t-cell,"CD8-positive, alpha-beta T cell",1
208,popv,CL:0000038,erythroid progenitor cell,1

In [38]:
# Transform df to fit requirements for HRA US#2 at https://apps.humanatlas.io/us2
df['percentage'] = df['cell_count'].apply(lambda c: c/df['cell_count'].sum())

# add more required column
df['modality'] = 'sc_transcriptomics'

# rename columns as needed
df_renamed = df.rename(columns=
  {
    'cell_count':'count'
  }
)

# New column order
new_order = ['tool', 'modality', 'percentage', 'count', 'cell_label','cell_id']

# Reassign columns
df = df_renamed[new_order]

df

,tool,modality,percentage,count,cell_label,cell_id
0,azimuth,sc_transcriptomics,0.052530,15017,regular ventricular cardiac myocyte,CL:0002131
1,azimuth,sc_transcriptomics,0.031483,9000,type II pneumocyte,CL:0002063
2,azimuth,sc_transcriptomics,0.029181,8342,fibroblast,CL:0000057
3,azimuth,sc_transcriptomics,0.021730,6212,monocyte-derived dendritic cell,CL:0011031
4,azimuth,sc_transcriptomics,0.019285,5513,type I pneumocyte,CL:0002062
...,...,...,...,...,...,...
204,popv,sc_transcriptomics,0.000010,3,alveolar type 2 fibroblast cell,CL:4028006
205,popv,sc_transcriptomics,0.000007,2,"CD8-positive, alpha-beta cytotoxic T cell",CL:0000794
206,popv,sc_transcriptomics,0.000003,1,CD141-positive myeloid dendritic cell,CL:0002394
207,popv,sc_transcriptomics,0.000003,1,"CD8-positive, alpha-beta T cell",ASCTB-TEMP:cd8-positive-alpha-beta-t-cell
208,popv,sc_transcriptomics,0.000003,1,erythroid progenitor cell,CL:0000038

In [40]:
# Export to CSV
df.to_csv('output/cell_summary.csv')