## Code to get HRApop and CTann counts for the 10th release

## Install and load libraries

In [1]:
%%capture
%pip install requests pandas

import requests
import pandas as pd
from io import StringIO

In [2]:
import warnings
warnings.filterwarnings('ignore')

## Global variables

In [3]:
hra_pop_version = 'v1.0'
branch = 'main'

## Load data

In [4]:
url = f'https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/refs/heads/{branch}/output-data/{hra_pop_version}/reports/universe-ad-hoc/sankey.csv'

df_sankey = pd.read_csv(url)
df_sankey

,portal,study_paper,doi,lead_author,is_azimuth_reference,donor_id,donor_sex,donor_age,donor_development_stage,donor_race,...,unique_dataset_id,link_to_h5ad_file,sc_transcriptomics_or_sc_proteomics,cell_type_annotation_tool,omap_id,number_of_cells_total,number_of_unique_cell_types,hubmap_dataset_publication_status,is_rui_registered,is_atlas_dataset
0,HCA,NaN,NaN,NaN,NaN,TSP27,Female,56.0,NaN,NaN,...,hhttps://api.cellxgene.cziscience.com/dp/v1/co...,https://cellxgene.cziscience.com/e/a357414d-20...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
1,KPMP,NaN,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,Donor1,Male,NaN,NaN,NaN,...,http://dx.doi.org/10.1681/ASN.2016091027#Donor...,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,NaN,NaN,NaN,NaN,True,False
2,KPMP,NaN,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,Donor2,Male,NaN,NaN,NaN,...,http://dx.doi.org/10.1681/ASN.2016091027#Donor...,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,NaN,NaN,NaN,NaN,True,False
3,KPMP,NaN,http://dx.doi.org/10.1681/ASN.2016091027,NaN,NaN,Donor3,Male,NaN,NaN,NaN,...,http://dx.doi.org/10.1681/ASN.2016091027#Donor...,http://dx.doi.org/10.1016/j.trsl.2017.07.006,NaN,NaN,NaN,NaN,NaN,NaN,True,False
4,HRA,NaN,NaN,NaN,NaN,Donor1,Female,38.0,NaN,NaN,...,http://purl.org/ccf/1.5/omap-1#Donor1_TissueBl...,https://hubmapconsortium.github.io/ccf-release...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22189,SPARC,NaN,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,Donor1,Female,49.0,NaN,NaN,...,https://sparc.science/datasets/390/version/1?d...,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22190,SPARC,NaN,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,Donor1,Female,49.0,NaN,NaN,...,https://sparc.science/datasets/390/version/1?d...,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22191,SPARC,NaN,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,Donor1,Female,49.0,NaN,NaN,...,https://sparc.science/datasets/390/version/1?d...,https://sparc.science/datasets/390/version/1?d...,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22192,KPMP,NaN,https://www.nature.com/articles/s41467-023-389...,NaN,NaN,Donor1,Male,NaN,NaN,NaN,...,https://zenodo.org/records/7653239#Donor1_Tiss...,https://zenodo.org/records/7653239,NaN,NaN,NaN,NaN,NaN,NaN,True,False
22193,KPMP,NaN,https://www.nature.com/articles/s41467-023-389...,NaN,NaN,Donor2,Female,NaN,NaN,NaN,...,https://zenodo.org/records/7653239#Donor2_Tiss...,https://zenodo.org/records/7653239,NaN,NaN,NaN,NaN,NaN,NaN,True,False

In [5]:
# could also use https://apps.humanatlas.io/api/grlc/hra-pop.html#get-/cell-types-in-atlas
url = f"https://raw.githubusercontent.com/x-atlas-consortia/hra-pop/refs/heads/{branch}/output-data/{hra_pop_version}/reports/atlas-ad-hoc/cell-types-in-anatomical-structurescts-per-as.csv"

headers = {
    'Accept': 'text/csv'
}

data = requests.get(url=url, headers=headers).text

df_as = pd.read_csv(StringIO(data))
df_as

,organ,as,as_label,sex,tool,modality,cell_id,cell_label,cell_count,cell_percentage,dataset_count
0,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_colonocyte,Colonocyte,1.205,0.147653,3
1,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_iga-plasma-cell,IgA plasma cell,1.182,0.144835,3
2,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_best4-epithelial,BEST4+ epithelial,0.699,0.085651,3
3,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_activated-cd4-t,Activated CD4 T,0.690,0.084548,3
4,large intestine,http://purl.obolibrary.org/obo/UBERON_0001052,rectum,Female,celltypist,sc_transcriptomics,https://purl.org/ccf/ASCTB-TEMP_ta,TA,0.540,0.066168,3
...,...,...,...,...,...,...,...,...,...,...,...
8891,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_0000097,Mast Cell,15322.464,0.024702,1
8892,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_4033039,CD8+ T Cell,3691.176,0.005951,1
8893,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,https://purl.org/ccf/ASCTB-TEMP_lymphatic-endo...,Lymphatic Endothelial (and some immune cells),1753.956,0.002828,1
8894,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,https://purl.org/ccf/ASCTB-TEMP_basal-epitheli...,Basal Epithelial Cell,970.104,0.001564,1
8895,lung,http://purl.org/sig/ont/fma/fma7508,Left posterior basal segmental bronchus,Male,sc_proteomics,sc_proteomics,http://purl.obolibrary.org/obo/CL_0000236,B Cell,462.144,0.000745,1

In [6]:
crosswalk_azimuth = pd.read_csv(
    'https://cdn.humanatlas.io/digital-objects/ctann/azimuth/v1.2/assets/azimuth-crosswalk.csv', skiprows=10)
crosswalk_azimuth

,Organ_Level,Organ_ID,Annotation_Label,Annotation_Label_ID,CL_Label,CL_ID,CL_Match
0,Heart_L2,UBERON:0000948,Adipocyte,AZ:0000001,adipocyte,CL:0000136,skos:exactMatch
1,Heart_L2,UBERON:0000948,Arterial Endothelial,AZ:0000002,endothelial cell of artery,CL:1000413,skos:exactMatch
2,Heart_L2,UBERON:0000948,Atrial Cardiomyocyte,AZ:0000003,regular atrial cardiac myocyte,CL:0002129,skos:exactMatch
3,Heart_L2,UBERON:0000948,B,AZ:0000004,B cell,CL:0000236,skos:exactMatch
4,Heart_L2,UBERON:0000948,Capillary Endothelial,AZ:0000005,capillary endothelial cell,CL:0002144,skos:exactMatch
...,...,...,...,...,...,...,...
759,Kidney,UBERON:0002113,Peritubular Capilary Endothelial,NaN,peritubular capillary endothelial cell,CL:1001033,skos:exactMatch
760,Bone_marrow,UBERON:0002371,CD8 Effector_1,NaN,"effector CD8-positive, alpha-beta T cell:1",CL:0001050,skos:narrowMatch
761,Bone_marrow,UBERON:0002371,CD8 Effector_2,NaN,"effector CD8-positive, alpha-beta T cell:2",CL:0001050,skos:narrowMatch
762,Bone_marrow,UBERON:0002371,CD8 Effector_3,NaN,"effector CD8-positive, alpha-beta T cell:3",CL:0001050,skos:narrowMatch
763,Bone_marrow,UBERON:0002371,T Proliferating,NaN,cycling T cell,CL:4033069,skos:exactMatch

In [7]:
crosswalk_celltypist = pd.read_csv(
    'https://cdn.humanatlas.io/digital-objects/ctann/celltypist/v1.1/assets/celltypist-crosswalk.csv', skiprows=10)
crosswalk_celltypist

,Organ_Level,Organ_ID,Annotation_Label,Annotation_Label_ID,CL_Label,CL_ID,CL_Match
0,blood_L1,UBERON:0000178,Age-associated B cells,CT:0000001,B cell:age-associated,CL:0000236,skos:narrowMatch
1,blood_L1,UBERON:0000178,C1 non-classical monocytes,CT:0000002,non-classical monocyte:C1,CL:0000875,skos:narrowMatch
2,blood_L1,UBERON:0000178,CD16+ NK cells,CT:0000003,"CD16-positive, CD56-dim natural killer cell, h...",CL:0000939,skos:exactMatch
3,blood_L1,UBERON:0000178,CD16- NK cells,CT:0000004,"CD16-negative, CD56-bright natural killer cell...",CL:0000938,skos:exactMatch
4,blood_L1,UBERON:0000178,Classical monocytes,CT:0000005,classical monocyte,CL:0000860,skos:exactMatch
...,...,...,...,...,...,...,...
888,Small_Intestine,UBERON:0002108,myofibroblast,NaN,myofibroblast cell,CL:0000186,skos:exactMatch
889,Small_Intestine,UBERON:0002108,myofibroblast (RSPO2+),NaN,myofibroblast cell:RSPO2+,CL:0000186,skos:narrowMatch
890,Small_Intestine,UBERON:0002108,pDC,NaN,plasmacytoid dendritic cell,CL:0000784,skos:exactMatch
891,Small_Intestine,UBERON:0002108,venous capillary,NaN,pre-venule capillary cell,CL:4047030,skos:exactMatch
892,Small_Intestine,UBERON:0002108,ÔøΩÔøΩ cells (INS+),NaN,cell:INS+,CL:0000000,skos:narrowMatch

In [8]:
crosswalk_popv = pd.read_csv(
    'https://cdn.humanatlas.io/digital-objects/ctann/popv/v1.2/assets/popv-crosswalk.csv', skiprows=10)
crosswalk_popv

,Organ_Level,Organ_ID,Annotation_Label,Annotation_Label_ID,CL_Label,CL_ID,CL_Match
0,blood,UBERON:0000178,CD141-positive myeloid dendritic cell,PV:0000001,CD141-positive myeloid dendritic cell,CL:0002394,skos:exactMatch
1,blood,UBERON:0000178,"CD4-positive, alpha-beta memory T cell",PV:0000002,"CD4-positive, alpha-beta memory T cell",CL:0000897,skos:exactMatch
2,blood,UBERON:0000178,"CD8-positive, alpha-beta T cell",PV:0000003,"CD8-positive, alpha-beta T cell",CL:0000625,skos:exactMatch
3,blood,UBERON:0000178,"CD8-positive, alpha-beta cytokine secreting ef...",PV:0000004,"CD8-positive, alpha-beta cytokine secreting ef...",CL:0000908,skos:exactMatch
4,blood,UBERON:0000178,T cell,PV:0000005,T cell,CL:0000084,skos:exactMatch
...,...,...,...,...,...,...,...
442,prostate gland,UBERON:0002367,bronchial epithelial cell,NaN,epithelial cell,CL:0000066,skos:narrowMatch
443,thymus,UBERON:0002370,"CD4-positive, CD25-positive, alpha-beta regula...",NaN,"CD4-positive, CD25-positive, alpha-beta regula...",CL:0000792,skos:exactMatch
444,thymus,UBERON:0002370,"CD4-positive, alpha-beta T cell",NaN,"CD4-positive, alpha-beta T cell",CL:0000624,skos:exactMatch
445,bone marrow,UBERON:0002371,"B cell, CD19-positive",NaN,"B cell, CD19-positive",CL:0001201,skos:exactMatch
446,mesenteric lymph node,UBERON:0002509,"CD4-positive, alpha-beta T cell",NaN,"CD4-positive, alpha-beta T cell",CL:0000624,skos:exactMatch

In [9]:
crosswalk_vccf = pd.read_csv(
    'https://cdn.humanatlas.io/digital-objects/ctann/vccf/v1.0/assets/vccf-crosswalk.csv', skiprows=10)
crosswalk_vccf

,Organ_Level,Organ_ID,Annotation_Label,Annotation_Label_ID,CL_Label,CL_ID,CL_Match
0,bonemarrow-codex-chop_L1,UBERON:0002371,VCCF:0000001,mesenchymal cell,mesenchymal cell,CL:0008019,skos:exactMatch
1,bonemarrow-codex-chop_L1,UBERON:0002371,VCCF:0000002,unknown cell,cell:unknown,CL:0000000,skos:narrowMatch
2,bonemarrow-codex-chop_L1,UBERON:0002371,VCCF:0000003,immune cell,leukocyte,CL:0000738,skos:exactMatch
3,bonemarrow-codex-chop_L1,UBERON:0002371,VCCF:0000004,hematopoeitic precursor cell,hematopoietic precursor cell,CL:0008001,skos:exactMatch
4,bonemarrow-codex-chop_L1,UBERON:0002371,VCCF:0000005,endothelial cell,endothelial cell,CL:0000115,skos:exactMatch
...,...,...,...,...,...,...,...
497,tonsil-codex-stanford_L3,UBERON:0002372,VCCF:0000498,squamous epithelial cell,squamous epithelial cell,CL:0000076,skos:exactMatch
498,tonsil-codex-stanford_L3,UBERON:0002372,VCCF:0000499,stromal cell,stromal cell,CL:0000499,skos:exactMatch
499,tonsil-codex-stanford_L3,UBERON:0002372,VCCF:0000500,t cell,T cell,CL:0000084,skos:exactMatch
500,NaN,NaN,VCCF:0000501,endothelial cell,endothelial cell,CL:0000115,skos:exactMatch
501,NaN,NaN,VCCF:0000502,endothelial cell of vascular tree,endothelial cell of vascular tree,CL:0002139,skos:exactMatch

In [10]:
# extract CL IDs and labels with tool
extract = ['Organ_ID', 'Annotation_Label',
           'Annotation_Label_ID', 'CL_ID', 'CL_Label', 'CL_Match']

# Extract the columns from each DataFrame
az_selected = crosswalk_azimuth[extract].assign(tool='azimuth')
ct_selected = crosswalk_celltypist[extract].assign(tool='celltypist')
popv_selected = crosswalk_popv[extract].assign(tool='popv')
vccf_selected = crosswalk_vccf[extract].assign(tool='vccf')

# Concatenate them into one DataFrame
df_crosswalks_combined = pd.concat(
    [az_selected, ct_selected, popv_selected, vccf_selected], ignore_index=True)

df_crosswalks_combined

,Organ_ID,Annotation_Label,Annotation_Label_ID,CL_ID,CL_Label,CL_Match,tool
0,UBERON:0000948,Adipocyte,AZ:0000001,CL:0000136,adipocyte,skos:exactMatch,azimuth
1,UBERON:0000948,Arterial Endothelial,AZ:0000002,CL:1000413,endothelial cell of artery,skos:exactMatch,azimuth
2,UBERON:0000948,Atrial Cardiomyocyte,AZ:0000003,CL:0002129,regular atrial cardiac myocyte,skos:exactMatch,azimuth
3,UBERON:0000948,B,AZ:0000004,CL:0000236,B cell,skos:exactMatch,azimuth
4,UBERON:0000948,Capillary Endothelial,AZ:0000005,CL:0002144,capillary endothelial cell,skos:exactMatch,azimuth
...,...,...,...,...,...,...,...
2601,UBERON:0002372,VCCF:0000498,squamous epithelial cell,CL:0000076,squamous epithelial cell,skos:exactMatch,vccf
2602,UBERON:0002372,VCCF:0000499,stromal cell,CL:0000499,stromal cell,skos:exactMatch,vccf
2603,UBERON:0002372,VCCF:0000500,t cell,CL:0000084,T cell,skos:exactMatch,vccf
2604,NaN,VCCF:0000501,endothelial cell,CL:0000115,endothelial cell,skos:exactMatch,vccf
2605,NaN,VCCF:0000502,endothelial cell of vascular tree,CL:0002139,endothelial cell of vascular tree,skos:exactMatch,vccf

In [11]:
# taken from https://github.com/hubmapconsortium/hra-workflows-runner/blob/main/src/gtex/downloader.js#L24-L48
ORGAN_MAPPING = {
    "UBERON:0001255": "bladder",
    "UBERON:0000178": "blood",
    "UBERON:0002371": "bone_marrow",
    "UBERON:0000970": "eye",
    "UBERON:0000948": "heart",
    "UBERON:0000059": "large_intestine",
    "UBERON:0002107": "liver",
    "UBERON:0002048": "lung",
    "UBERON:0000029": "lymph_node",  # original note: could be UBERON:0002509?
    "UBERON:0001911": "breast",      # 'mammary' also maps to this ID
    "UBERON:0001264": "pancreas",
    "UBERON:0002367": "prostate",
    "UBERON:0002097": "skin",
    "UBERON:0002108": "small_intestine",
    "UBERON:0002106": "spleen",
    "UBERON:0002370": "thymus",
    "UBERON:0003126": "trachea",
    "UBERON:0000995": "uterus",
    "UBERON:0004537": "vasculature",
    "UBERON:0002469": "esophagus mucosa",
    "UBERON:0004648": "esophagus muscularis",
    "UBERON:0001134": "skeletal muscle",
    "UBERON:0002113": "kidney",  # manually added
    "UBERON:0001347": "white adipose tissue",  # manually added
    "UBERON:0002373": "palatine tonsil",  # manually added
    "UBERON:0001013": "adipose tissue",  # manually added
    "UBERON:0001384": "primary motor cortex",  # manually added
    "UBERON:0002421": "hippocampal formation",  # manually added
    "UBERON:0000006": "islets of Langerhans",    # manually added
    "UBERON:0000160": "intestine",                    # manually added
    "UBERON:0000079": "male reproductive organ",       # manually added
    "UBERON:0001004": "respiratory system",             # manually added
    "UBERON:0001723": "tongue",                         # manually added
    "UBERON:0002509": "mesenteric lymph node",           # manually added
    "UBERON:0000167": "oral cavity",                    # manually added
    "UBERON:0001043": "esophagus",                      # manually added
    "UBERON:0002372": "tonsil",  # manually added
    "UBERON:0002450": "decidua"  # manually added


}


def try_get_organ_label(id: str):
  try:
    result = ORGAN_MAPPING[id]
    return result
  except:
    print(f'no match for {id}')
    return id

## HRApop dataset counts from Sankey data

In [12]:
organ_counts = (
    df_sankey[df_sankey['is_atlas_dataset'] == True].drop_duplicates(['unique_dataset_id'])['organ_name']
    .value_counts()
    .reset_index()
)

organ_counts.columns = ['organ_name', 'count']
organ_counts

                                   organ_name  count
0                                       heart    111
1                             large intestine    104
2                                right kidney    101
3                          respiratory system     93
4                                 left kidney     92
5                             small intestine     78
6                                      spleen     19
7                                skin of body     17
8                                 left ureter     13
9                             urinary bladder     12
10                   male reproductive system      6
11                                     thymus      4
12  Set of lactiferous glands in right breast      3
13                               right ureter      3
14   Set of lactiferous glands in left breast      2
15                                   pancreas      2
16                                      liver      2

## 3D AS counts

In [13]:
as_counts = (
    df_as.drop_duplicates(['as_label'])['organ']
    .value_counts()
    .reset_index()
)

as_counts.columns = ['organ', 'count']
as_counts

                  organ  count
0                  lung     18
1       small intestine      8
2       large intestine      7
3           Left kidney      6
4                 heart      6
5              prostate      6
6              pancreas      5
7                spleen      3
8    Left mammary gland      3
9                 liver      3
10               thymus      2
11      urinary bladder      2
12         Right ureter      1
13          Left ureter      1
14                 skin      1
15  Right mammary gland      1

## CTann counts from crosswalks

In [14]:
pivot_df = (
    df_crosswalks_combined.groupby('tool')['Organ_ID']
    .agg(lambda x: sorted(set(try_get_organ_label(str(v)) for v in x.dropna())))
    .reset_index()
)

long_df = pivot_df.explode('Organ_ID').reset_index(drop=True)

long_df

       tool        Organ_ID
0   azimuth  adipose tissue
1   azimuth           blood
2   azimuth     bone_marrow
3   azimuth           heart
4   azimuth          kidney
..      ...             ...
57     vccf     oral cavity
58     vccf        pancreas
59     vccf            skin
60     vccf          spleen
61     vccf          tonsil

[62 rows x 2 columns]

In [15]:
long_df.groupby('Organ_ID').size()

Organ_ID
adipose tissue             2
bladder                    1
blood                      3
bone_marrow                4
breast                     1
decidua                    1
esophagus                  1
eye                        1
heart                      3
hippocampal formation      1
intestine                  2
islets of Langerhans       1
kidney                     2
large_intestine            2
liver                      3
lung                       4
lymph_node                 3
male reproductive organ    1
mesenteric lymph node      1
oral cavity                1
palatine tonsil            1
pancreas                   4
primary motor cortex       1
prostate                   1
respiratory system         1
skeletal muscle            1
skin                       3
small_intestine            2
spleen                     3
thymus                     1
tongue                     1
tonsil                     1
trachea                    1
uterus                     1
vasculature                1
white adipose tissue       1
dtype: int64